import os
import argparse
import scipy.io as sio
import numpy as np
from pyFM.mesh import TriMesh

def get_quality_label(error):
    """Standard DV-Matcher / Princeton scale for sqrt(Area) normalization."""
    if error < 0.02: return "Excellent (SOTA)"
    elif error < 0.05: return "Very good"
    elif error < 0.1: return "Good"
    elif error < 0.2: return "Moderate"
    else: return "Poor"

def main():
    parser = argparse.ArgumentParser(description="Evaluate Geodesic Error on SHREC '19 Shape Correspondence")
    parser.add_argument('--p2p_dir', type=str, default='./p2p_results_st_te_SHREC/', help='Directory with predicted p2p .txt files')
    parser.add_argument('--off_dir', type=str, default='./input/SHREC/off/', help='Directory with .off mesh files')
    parser.add_argument('--mat_dir', type=str, default='./input/SHREC/mat/', help='Directory with .mat geodesic distance matrices')
    parser.add_argument('--map_dir', type=str, default='./input/SHREC/map/', help='Directory with ground-truth .map files')
    args = parser.parse_args()

    off_dir = args.off_dir
    mat_dir = args.mat_dir
    map_dir = args.map_dir
    p2p_dir = args.p2p_dir

    if not os.path.exists(p2p_dir):
        print(f"[!] Prediction directory not found: {p2p_dir}")
        return

    # 1. Get all .off files and sort them
    all_off_files = sorted([f for f in os.listdir(off_dir) if f.endswith('.off')])
    mesh_names = [os.path.splitext(f)[0] for f in all_off_files]

    results_log = []
    all_raw_errors = []

    print(f"\nEvaluating SHREC '19 correspondences from: {p2p_dir}")
    print(f"{'Source':<8} | {'Target':<8} | {'Geo Error':<10}")
    print("-" * 45)

    # ====== 44x44 NESTED LOOP ======
    for src_name in mesh_names:
        for tgt_name in mesh_names:
            if src_name == tgt_name:
                continue
                
            # p2p_{TARGET}_to_{SOURCE}.txt contains map: SOURCE -> TARGET
            map_filename = f"{src_name}_{tgt_name}.map"
            p2p_filename = f"p2p_{tgt_name}_to_{src_name}.txt"
            
            map_path = os.path.join(map_dir, map_filename)
            p2p_path = os.path.join(p2p_dir, p2p_filename)

            # Skip if Ground Truth or Prediction doesn't exist for this pair
            if not os.path.exists(map_path) or not os.path.exists(p2p_path):
                continue

            try:
                # 2. Load Target Mesh & Calculate Area Normalization
                mesh_target = TriMesh(os.path.join(off_dir, f"{tgt_name}.off"), area_normalize=False)
                norm_factor = np.sqrt(mesh_target.area)

                # 3. Load Distance Matrix of Target
                dist_matrix = sio.loadmat(os.path.join(mat_dir, f"{tgt_name}.mat"))['dist']
                num_tgt_v = dist_matrix.shape[0]

                # 4. Load Ground Truth Map (Source -> Target)
                # Official SHREC .map files are 1-based (from MATLAB). Convert to 0-based.
                gt_map = np.loadtxt(map_path, dtype=np.int32)
                if gt_map.max() >= num_tgt_v or (gt_map.min() >= 1 and 0 not in gt_map):
                    gt_map = gt_map - 1
                
                # 5. Load Predicted P2P (Source -> Target)
                # Predictions generated by Python np.argmax are inherently 0-based.
                txt_data = np.genfromtxt(p2p_path, dtype=int)
                p2p_preds = txt_data[:, 1]
                # Only shift if predictions were generated 1-based (> max valid index)
                if p2p_preds.max() >= num_tgt_v:
                    p2p_preds = p2p_preds - 1

                # 6. Align arrays: find how many vertices we can compare
                num_compare = min(len(gt_map), len(p2p_preds))
                gt_indices = gt_map[:num_compare]
                pred_indices = p2p_preds[:num_compare]

                valid_mask = (gt_indices < num_tgt_v) & (pred_indices < num_tgt_v) & \
                             (gt_indices >= 0) & (pred_indices >= 0)
                
                if not np.any(valid_mask):
                    print(f"{src_name:<8} | {tgt_name:<8} | ERROR: No valid indices found")
                    continue

                # 7. Geodesic Calculation
                raw_errors = dist_matrix[gt_indices[valid_mask], pred_indices[valid_mask]]
                norm_errors = raw_errors / norm_factor
                final_error = norm_errors.mean()
                
                all_raw_errors.extend(norm_errors)
                results_log.append({
                    'source': src_name,
                    'target': tgt_name,
                    'error': final_error,
                    'mat': f"{tgt_name}.mat"
                })
                
                print(f"{src_name:<8} | {tgt_name:<8} | {final_error:.6f}")

            except Exception as e:
                print(f"{src_name:<8} | {tgt_name:<8} | ERROR: {str(e)}")

    # ====== FINAL AGGREGATION ======
    if results_log:
        all_errs = [r['error'] for r in results_log]
        avg_total = np.mean(all_errs)
        sorted_results = sorted(results_log, key=lambda x: x['error'])

        # Percentage of correspondences within thresholds (KIM curve points)
        all_raw_arr = np.array(all_raw_errors)
        pck_02 = (all_raw_arr < 0.02).mean() * 100.0
        pck_05 = (all_raw_arr < 0.05).mean() * 100.0
        pck_10 = (all_raw_arr < 0.10).mean() * 100.0

        print("\n" + "="*55)
        print(f"SHREC '19 BENCHMARK SUMMARY ({len(results_log)} valid GT pairs)")
        print(f"OVERALL MEAN GEODESIC ERROR: {avg_total:.6f}")
        print(f"Overall Quality Category:   {get_quality_label(avg_total)}")
        print("-" * 55)
        print(f"Correspondences < 0.02 (strict):  {pck_02:.2f}%")
        print(f"Correspondences < 0.05 (medium):  {pck_05:.2f}%")
        print(f"Correspondences < 0.10 (loose):   {pck_10:.2f}%")
        print("="*55)

        print("\nTOP 5 BEST MATCHES (Min Error):")
        for i, res in enumerate(sorted_results[:5]):
            print(f"#{i+1} | {res['error']:.6f} | {res['source']} -> {res['target']}")
    else:
        print("\n[!] No matching .map and .txt pairs found.")

if __name__ == "__main__":
    main()